# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/xujia/onedrive/surfacebook/project/fpga/icgtrmm1/control_blocks/control_blocks/mbs_v1/microblazeserver.tmp/udp_v2_project/UDP_v2_project.cache/wt [current_project]
set_property parent.project_path c:/users/xujia/onedrive/surfacebook/project/fpga/icgtrmm1/control_blocks/control_blocks/mbs_v1/microblazeserver.tmp/udp_v2_project/UDP_v2_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_repo_paths c:/Users/xujia/OneDrive/SurfaceBook/Project/FPGA/ICGTRMM1/Control_Blocks/Control_Blocks/IPs [current_project]
set_property ip_output_repo c:/users/xujia/onedrive/surfacebook/project/fpga/icgtrmm1/control_blocks/control_blocks/mbs_v1/microblazeserver.tmp/udp_v2_project/UDP_v2_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  c:/Users/xujia/OneDrive/SurfaceBook/Project/FPGA/ICGTRMM1/Control_Blocks/Control_Blocks/IPs/UDP_V2/ip_repo/UDP_2/hdl/UDP_v2_S00_AXI.v
  c:/Users/xujia/OneDrive/SurfaceBook/Project/FPGA/ICGTRMM1/Control_Blocks/Control_Blocks/IPs/UDP_V2/ip_repo/UDP_2/hdl/UDP_v2.v
}
read_vhdl -library xil_defaultlib {
  c:/Users/xujia/OneDrive/SurfaceBook/Project/FPGA/ICGTRMM1/Control_Blocks/Control_Blocks/IPs/UDP_V2/ip_repo/UDP_2/src/Interface.vhd
  c:/Users/xujia/OneDrive/SurfaceBook/Project/FPGA/ICGTRMM1/Control_Blocks/Control_Blocks/IPs/UDP_V2/ip_repo/UDP_2/src/data.vhd
  c:/Users/xujia/OneDrive/SurfaceBook/Project/FPGA/ICGTRMM1/Control_Blocks/Control_Blocks/IPs/UDP_V2/ip_repo/UDP_2/src/i_add_crc32.vhd
  c:/Users/xujia/OneDrive/SurfaceBook/Project/FPGA/ICGTRMM1/Control_Blocks/Control_Blocks/IPs/UDP_V2/ip_repo/UDP_2/src/i_add_preamble.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top UDP_v2 -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef UDP_v2.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file UDP_v2_utilization_synth.rpt -pb UDP_v2_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
