webtalk_init -webtalk_dir D:\\GMJ_SDK\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-08-26 14:47:20" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211734211_0_0_470" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "925kpd49q1fon8nr3gbso5pi8l" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.1_22" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.468 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1566843517065" -context "sdk\\\\bsp/1566843517065"
webtalk_add_data -client sdk -key hwid -value "1566842537054" -context "sdk\\\\bsp/1566843517065"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1566843517065"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1566843517065"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1566843517065"
webtalk_add_data -client sdk -key uid -value "1566843522316" -context "sdk\\\\application/1566843522316"
webtalk_add_data -client sdk -key hwid -value "1566842537054" -context "sdk\\\\application/1566843522316"
webtalk_add_data -client sdk -key bspid -value "1566843517065" -context "sdk\\\\application/1566843522316"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1566843522316"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1566843522316"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1566843522316"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1566843522316"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1566843522316"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1566843522316"
webtalk_add_data -client sdk -key projSize -value "84.75390625" -context "sdk\\\\application/1566843522316"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1566845240153"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1566845240153"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1566845240153"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1566845240153"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1566845240153"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1566845240153"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1566845240153"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1566845240153"
webtalk_transmit -clientid 2527727530 -regid "211734211_0_0_470" -xml D:\\GMJ_SDK\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\GMJ_SDK\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\GMJ_SDK\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
